chore : fix not null violation issue when creating fake chats for showing it on chat's index page
MrPunyapal/livewire-chat-app pull request #3
Opened 2024-09-12 18:18 UTC by JaiveerChavda

This PR fixes , integrity constraint violation: 19 NOT NULL chats.room_id issue.
actually when uncommenting chat factory line, creates this issue as it's not creating room record and try to insert hardcode id which doesn't exists. 

merging this issue will provide quicker development on chat module

![image](https://github.com/user-attachments/assets/77ba26e2-549c-4086-b781-eff7582f93a2)

2024-09-17 16:02 UTC, MrPunyapal requested changes

2024-09-17 16:02 UTC, MrPunyapal commented on app/Livewire/Chats/Index.php
> +        $this->roomId = 1;
Can you also add the same id here? 🤔

2024-09-18 16:17 UTC, JaiveerChavda commented on app/Livewire/Chats/Index.php
> +        $this->roomId = 1;
sure , i wiil and sorry for late response

2024-09-18 16:18 UTC, JaiveerChavda commented on app/Livewire/Chats/Index.php
> +        $this->roomId = 1;
BTW , what you're thoughts on streamlining this process of making room , chat and member in database seeder

2024-09-18 16:33 UTC, MrPunyapal commented on app/Livewire/Chats/Index.php
> +        $this->roomId = 1;
We will remove all these comments and add seeders in the end.

These or all are for current development purpose 🫡

2024-09-18 16:38 UTC, JaiveerChavda commented on app/Livewire/Chats/Index.php
> +        $this->roomId = 1;
okay got it.

2024-09-22 11:35 UTC, MrPunyapal commented on app/Livewire/Chats/Index.php
> +        assert($user instanceof User);
we don't user assert()

2024-09-22 11:36 UTC, MrPunyapal commented on app/Models/Room.php
> +    protected $fillable = [
we don't user fillable. (we will add unguarded in service provider later)

2024-09-22 11:37 UTC, MrPunyapal commented
let skip this for now.

2024-09-22 11:37 UTC, closed without merging

2024-09-22 12:35 UTC, JaiveerChavda commented
okay, then how can we fix this current user issue.

2024-09-22 12:38 UTC, MrPunyapal commented
Right now it's just for listing purposes.
So if you first add some rooms for side bar then you must have some rooms so you also have room with id 1.

2024-09-22 13:03 UTC, JaiveerChavda commented
got it.